### ISSUE TITLE
'../AppEvents/Internal/ViewHierarchy/FBSDKViewHierarchy.h' file not found 

### ISSUE THREAD

**Issue by WillLewis** [facebook/facebook-ios-sdk#1283]
###  environment
  *Cocoapods 1.9.1
  * Xcode version: 11.3.1
  * Firebase SDK version: 6.2
  * Firebase Component: FBSDKCoreKit + Internal.h
  * Component version: 6.6.0
  * Installation method: CocoaPods 

### problem
'../AppEvents/Internal/ViewHierarchy/FBSDKViewHierarchy.h' file not found

<img width="1584" alt="Screen Shot 2020-03-10 at 6 45 46 PM" src="https://user-images.githubusercontent.com/789554/76368801-617d3700-62ff-11ea-986f-76e0669d4805.png">

### to reproduce:**Actual Issue**
CompileC /Users/WL/Library/Developer/Xcode/DerivedData/FriendlyChatSwift-hexxjipfkpivmdcldgydlnjdqdwv/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBSDKLoginKit.build/Objects-normal/x86_64/FBSDKLoginError.o /Users/WL/Desktop/NANO/OnParApp/OnPar/Pods/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginKit/Internal/FBSDKLoginError.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'FBSDKLoginKit' from project 'Pods')
    cd /Users/WL/Desktop/NANO/OnParApp/OnPar/Pods
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -target x86_64-apple-ios8.0-simulator -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu11 -fobjc-arc -fobjc-weak -fmodules -gmodules -fmodules-cache-path=/Users/WL/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/WL/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -fmodule-name=FBSDKLoginKit -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DPOD_CONFIGURATION_DEBUG=1 -DDEBUG=1 -DCOCOAPODS=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -Wunguarded-availability -fobjc-abi-version=2 -fobjc-legacy-dispatch -index-store-path /Users/WL/Library/Developer/Xcode/DerivedData/FriendlyChatSwift-hexxjipfkpivmdcldgydlnjdqdwv/Index/DataStore -iquote /Users/WL/Library/Developer/Xcode/DerivedData/FriendlyChatSwift-hexxjipfkpivmdcldgydlnjdqdwv/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBSDKLoginKit.build/FBSDKLoginKit-generated-files.hmap -I/Users/WL/Library/Developer/Xcode/DerivedData/FriendlyChatSwift-hexxjipfkpivmdcldgydlnjdqdwv/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBSDKLoginKit.build/FBSDKLoginKit-own-target-headers.hmap -I/Users/WL/Library/Developer/Xcode/DerivedData/FriendlyChatSwift-hexxjipfkpivmdcldgydlnjdqdwv/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBSDKLoginKit.build/FBSDKLoginKit-all-non-framework-target-headers.hmap -ivfsoverlay /Users/WL/Library/Developer/Xcode/DerivedData/FriendlyChatSwift-hexxjipfkpivmdcldgydlnjdqdwv/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBSDKLoginKit.build/all-product-headers.yaml -iquote /Users/WL/Library/Developer/Xcode/DerivedData/FriendlyChatSwift-hexxjipfkpivmdcldgydlnjdqdwv/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBSDKLoginKit.build/FBSDKLoginKit-project-headers.hmap -I/Users/WL/Library/Developer/Xcode/DerivedData/FriendlyChatSwift-hexxjipfkpivmdcldgydlnjdqdwv/Build/Products/Debug-iphonesimulator/FBSDKLoginKit/include -I/Users/WL/Library/Developer/Xcode/DerivedData/FriendlyChatSwift-hexxjipfkpivmdcldgydlnjdqdwv/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBSDKLoginKit.build/DerivedSources-normal/x86_64 -I/Users/WL/Library/Developer/Xcode/DerivedData/FriendlyChatSwift-hexxjipfkpivmdcldgydlnjdqdwv/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBSDKLoginKit.build/DerivedSources/x86_64 -I/Users/WL/Library/Developer/Xcode/DerivedData/FriendlyChatSwift-hexxjipfkpivmdcldgydlnjdqdwv/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBSDKLoginKit.build/DerivedSources -F/Users/WL/Library/Developer/Xcode/DerivedData/FriendlyChatSwift-hexxjipfkpivmdcldgydlnjdqdwv/Build/Products/Debug-iphonesimulator/FBSDKLoginKit -F/Users/WL/Library/Developer/Xcode/DerivedData/FriendlyChatSwift-hexxjipfkpivmdcldgydlnjdqdwv/Build/Products/Debug-iphonesimulator/FBSDKCoreKit -include /Users/WL/Desktop/NANO/OnParApp/OnPar/Pods/Target\ Support\ Files/FBSDKLoginKit/FBSDKLoginKit-prefix.pch -MMD -MT dependencies -MF /Users/WL/Library/Developer/Xcode/DerivedData/FriendlyChatSwift-hexxjipfkpivmdcldgydlnjdqdwv/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBSDKLoginKit.build/Objects-normal/x86_64/FBSDKLoginError.d --serialize-diagnostics /Users/WL/Library/Developer/Xcode/DerivedData/FriendlyChatSwift-hexxjipfkpivmdcldgydlnjdqdwv/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBSDKLoginKit.build/Objects-normal/x86_64/FBSDKLoginError.dia -c /Users/WL/Desktop/NANO/OnParApp/OnPar/Pods/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginKit/Internal/FBSDKLoginError.m -o /Users/WL/Library/Developer/Xcode/DerivedData/FriendlyChatSwift-hexxjipfkpivmdcldgydlnjdqdwv/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBSDKLoginKit.build/Objects-normal/x86_64/FBSDKLoginError.o

In file included from /Users/WL/Desktop/NANO/OnParApp/OnPar/Pods/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginKit/Internal/FBSDKLoginError.m:21:
/Users/WL/Desktop/NANO/OnParApp/OnPar/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/FBSDKCoreKit+Internal.h:102:9: fatal error: '../AppEvents/Internal/ViewHierarchy/FBSDKViewHierarchy.h' file not found
#import "../AppEvents/Internal/ViewHierarchy/FBSDKViewHierarchy.h"
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

### Relevant code...Below is my podfile
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
use_frameworks!

pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Messaging'
pod 'Firebase/InAppMessaging'
pod 'Firebase/Storage'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/RemoteConfig'
pod 'FirebaseUI'

target 'FriendlyChatSwift' do
end

### And here is the output from a pod update:
The following pod updates are available:
- FBSDKLoginKit 4.44.1 -> 5.15.1 (latest version 6.2.0)
- Firebase 6.15.0 -> (unused) (latest version 6.19.0)
- FirebaseAnalytics 6.2.1 -> 6.3.1 (latest version 6.3.1)
- FirebaseCore 6.6.0 -> 6.6.4 (latest version 6.6.4)
- FirebaseCoreDiagnostics 1.2.1 -> 1.2.2 (latest version 1.2.2)
- FirebaseInAppMessaging 0.16.0 -> 0.19.0 (latest version 0.19.0)
- FirebaseMessaging 4.2.1 -> 4.3.0 (latest version 4.3.0)
- FirebaseStorage 3.5.0 -> 3.6.0 (latest version 3.6.0)
- FirebaseUI 4.1.1 -> 8.4.2 (latest version 8.4.2)
- GoogleAppMeasurement 6.2.1 -> 6.3.1 (latest version 6.3.1)
- GoogleDataTransport 4.0.1 -> 5.0.0 (latest version 5.0.0)
- GoogleDataTransportCCTSupport 1.4.1 -> 2.0.0 (latest version 2.0.0)
- GoogleSignIn 4.4.0 -> 5.0.2 (latest version 5.0.2)
- SDWebImage 4.4.8 -> 5.6.0 (latest version 5.6.0)
- TwitterCore 2.8.0 -> (unused) (latest version 3.2.0)
- TwitterKit 2.8.1 -> (unused) (latest version 3.4.2)
```

```

**Comment by advanceTheCoder** [comment]
I'm having the same issue, did you managed to solve this?

**Comment by SanaAhmed** [comment]
I'm having the same issue anyone has a solution to this?

**Comment by dentikhomirov** [comment]
Hi there. I found solution that helps me with issue.
1. add to podfile next lines:
```
pod 'FBSDKLoginKit', '6.0.0'
pod 'FacebookSDK', '6.0.0'

```
2. next in console do `pod deintegrate`
3. last action is `pod install`
If it doesn't help you, delete derived data and clean project

**Comment by advanceTheCoder** [comment]
I'm getting this error:

[!] CocoaPods could not find compatible versions for pod "FBSDKLoginKit":
      In Podfile:
        FBSDKLoginKit (= 6.0.0)

        flutter_facebook_login (from `.symlinks/plugins/flutter_facebook_login/ios`)
        was resolved to 0.0.1, which depends on
          FBSDKLoginKit (= 4.39.1)

**Comment by dentikhomirov** [comment]
firstly deintegrate your pods, then try to remove versions from `FBSDKLoginKit` in podfile and let him select version and try to run project
It is possible variant of what you should try to do. Steps, which helped me, are described in previous message. 
And maybe something unusual in `flutter_facebook_login`. Don't use flutter with Facebook integration yet.

**Comment by SanaAhmed** [comment]
I tried your steps but they didn't work for me still getting the same error. However, in my pod file I have

pod 'FBSDKLoginKit'

**Comment by SanaAhmed** [comment]
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "FBSDKLoginKit":
  In Podfile:
    FBSDKLoginKit (= 6.0.0)

    FirebaseUI/Facebook was resolved to 6.2.1, which depends on
      FBSDKLoginKit (~> 4.35)

**Comment by artud2000** [comment]
I'm having the same issue

**Comment by artud2000** [comment]
Any updates on this?

**Comment by JoshuaFry** [comment]
For people using flutter, updating to flutter_facebook_login: ^3.0.0 from ^1.2.0 in public.yaml solved this issue for me.

**Comment by SanaAhmed** [comment]
Updating and all its dependent liberaries solved it for me
pod 'FBSDKLoginKit', '6.0.0'

**Comment by ebarrera95** [comment]
@SanaAhmed It worked for me, thanks

**Comment by artud2000** [comment]
Still seeing this error

I'm doing

```
def fb_sdk_dependencies
  pod 'FBAudienceNetwork', '~> 5.8.0'
  pod 'FBSDKCoreKit', '~> 6.0.0'
  pod 'FBSDKLoginKit', '~> 6.0.0'
  pod 'FBSDKShareKit', '~> 6.0.0'
end
```


```
Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/FBSDKCoreKit+Internal.h:102:9:
[31m'../AppEvents/Internal/ViewHierarchy/FBSDKViewHierarchy.h' file not found[0m

#import "../AppEvents/Internal/ViewHierarchy/FBSDKViewHierarchy.h"
```

**Comment by artud2000** [comment]
I'm also seeing

```
Running script '[CP] Check Pods Manifest.lock'
18:54:58 
18:54:58 ❌  error: unable to spawn process (Argument list too long)
```

**Comment by roock3r** [comment]
I had that issue using flutter_facebook_login version  1.1.1 , changed my pub spec file to use version 2.0.0 , did a build clean , then deleted the podfile.lock and the Pods directory. Then did a pub get and it ran successfully. Hope this helps.

**Comment by artud2000** [comment]
I can't fix this issue :/ I have tried all the above suggestions.

**Comment by SanaAhmed** [comment]
@artud2000 try removing version specifiers 

def fb_sdk_dependencies
  pod 'FBAudienceNetwork'
  pod 'FBSDKCoreKit' 
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
end

**Comment by artud2000** [comment]
@SanaAhmed  I have tried that but it didn't work, I'm going to kick a pod install, but I'm going to try to revert the changes that pods makes to my pbproj file and I will also remove the changes to FBSDKCoreKit+Internal.h and see if that fixes it.

**Comment by Nids-go** [comment]
> 
> 
> For people using flutter, updating to flutter_facebook_login: ^3.0.0 from ^1.2.0 in public.yaml solved this issue for me.

Yes. I was using old version of flutter_facebook_login. Thanks. Worked for me.

**Comment by artud2000** [comment]
Fixed my issue by removing the relative paths inside `FBSDKCoreKit+Internal.h`

For example:

`#import "../AppEvents/Internal/FBSDKAppEvents+Internal.h"` 
for 
`#import "FBSDKAppEvents+Internal.h"`

**Comment by RameshSain** [comment]
https://github.com/firebase/firebase-ios-sdk/issues/5062

**Comment by DevTulon** [comment]
I am facing the exact same issue. Help!

**Comment by sonhd92** [comment]
Bump it up. Still got this issue when using FirebaseUI/Facebook latest version
