### ISSUE TITLE
After the Limited Login the firstName and lastName are nil in Profile

### ISSUE THREAD

**Issue by gfoldv** [facebook/facebook-ios-sdk#1657]
## Checklist

- [x] I've updated to the latest released version of the SDK
- [x] I've searched for existing [GitHub issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [x] I've looked for existing answers on [Stack Overflow](https://facebook.stackoverflow.com), the [Facebook Developer Community Forum](https://developers.facebook.com/community/) and the [Facebook Developers Group](https://www.facebook.com/groups/fbdevelopers)
- [x] I've read the [Code of Conduct](https://github.com/facebook/facebook-ios-sdk/blob/master/CODE_OF_CONDUCT.md)
- [x] This issue is not security related and can safely be disclosed publicly on GitHub

## Environment

Describe your dev environment here, giving as many details as possible. If you have them, make sure to include:

- Xcode Version: `12.4`
- Swift Version: `5` (if issue is Swift related)
- Installation Platform & Verison: `Cocoapods` version `1.10.0`
- Facebook iOS SDK `9.0.1`

## Goals

I want to receive the First Name and Last Name after the Limited Login

## Expected Results

First Name and Last Name are available

## Actual Results

The firstName and lastName properties in the Profile are nil

**Comment by joesus** [comment]
There is not enough information here to help debug the issue. Please report this to our designated developer support team -- https://developers.facebook.com/support/bugs/ -- as this will help us get more information and resolve it more quickly.

**Comment by gfoldv** [comment]
There is not much to debug here

**FBSDKLoginCompletion.m**

```
+ (nullable FBSDKProfile *)profileWithClaims:(FBSDKAuthenticationTokenClaims *)claims
{
  if (claims.sub.length == 0) {
    return nil;
  }

  NSURL *imageURL;
  if (claims.picture) {
    imageURL = [NSURL URLWithString:claims.picture];
  }

  return [[FBSDKProfile alloc] initWithUserID:claims.sub
                                    firstName:nil
                                   middleName:nil
                                     lastName:nil
                                         name:claims.name
                                      linkURL:nil
                                  refreshDate:nil
                                     imageURL:imageURL
                                        email:claims.email];
```

Please re-open.

**Comment by joesus** [comment]
> There is not much to debug here

This code can be used in a variety of ways and environments. Please provide a reproducible sample.

**Comment by gfoldv** [comment]
[FacebookLoginSample.zip](https://github.com/facebook/facebook-ios-sdk/files/6031656/FacebookLoginSample.zip)

This is a simlified version of the FacebookLoginSample. After login the Current Login Details screen shows the First Name and Last Name placeholders with bold font. According to the code both are "Current Profile unavailable".

**Comment by gfoldv** [comment]
@joesus Is the sample helpful to progress further with this ticket?

**Comment by isimpson** [comment]
Hi, did you ever resolve this @gfoldv as I am trying the limited login also with the latest iOS FB SDK v9.0.1.
The login call returns success but the Profile does not contain first name, last name or email even though the user has given those permissions to the app, all are nil.
Also using Xcode 12.4.
@joesus please reopen this ticket or provide a solution thanks.

**Comment by gfoldv** [comment]
@isimpson The e-mail is filled in the Profile, I personally get that back. I have included the piece of code above, which clearly shows that the separate name fields in the Profile are not propagated with values. Actually at that point, the claims also does not contain these fields.

**Comment by isimpson** [comment]
I am using the following code and dont even get the email following a users login with a sandbox tester:
```
                let login = LoginManager()
                guard let configuration = LoginConfiguration(permissions: ["email", "public_profile"], tracking: .limited, nonce: "123") else { return }
                login.logIn(configuration: configuration) { result in
                    switch result {
                        case .cancelled, .failed:
                            // Failed or cancelled
                            break
                        case .success:
                            // All the following are nil...
                            let firstName = Profile.current?.firstName
                            let lastName = Profile.current?.lastName
                            let email = Profile.current?.email
                            // Token looks ok and is non-nil...
                            let tokenString = AuthenticationToken.current?.tokenString
                    }
                }

```

**Comment by gfoldv** [comment]
I have just checked it. You are right, no e-mail. In my memory it was provided when I created this ticket. Maybe backend has been changed since.

**Comment by tschob** [comment]
I believe the email is not returned because the limited mode is used. I receive an email if i chose tracking as `enabled`.
I received a token with an email a few weeks ago, I am now not sure if the limited login mode was working back then or if it was simply also from a request with tracking enabled.

**Comment by tschob** [comment]
@isimpson The access for the email scope was granted and it's also contained in the token and profile if tracking is enabled, it's only missing if the limited tracking mode is enabled

**Comment by isimpson** [comment]
@tschob according to the documentation it should also be returned in case of limited tracking mode.

**Comment by tschob** [comment]
Yes, it looks like a bug. I am preparing myself currently to open a bug report 😞

**Comment by joesus** [comment]
We have fixed the issue. It should reach all users in the next few hours. Thank you for bringing this to our attention.

**Comment by gfoldv** [comment]
@joesus Thank you for the effort to bring the e-mail back, although this ticket is about the missing First and Last name field values.

**Comment by joesus** [comment]
I see... so there's a couple things happening.

For limited login we don't expect to get a separate first and last name. The claims on the authentication token currently only support a 'name'.

It does appear there is a separate bug in terms of the ability to use `Profile`'s `loadProfileWithToken` method... if you've logged in with limited tracking then there's a profile with a user id populated from the authentication token. If you log in before the 24 hour expiration with with non-limited tracking and then try to use the `loadProfileWithToken` method, it will not fetch because there will be a current profile that has the same user id as the access token.

I'll see to that but in the meantime I'm not sure this is a bug since it is not a regression and was not intended to work the way you've described. Future releases may add this capability. Happy to pass along the feedback. Thanks!

**Comment by isimpson** [comment]
@joesus thanks for the support and indeed email is being returned correctly now but as @gfoldv mentioned the first name and last name are not.
Now the documentation states that the `Profile.current?.firstName` and `Profile.current?.lastName` should be returned and currently are not as per this bug so please re-open this issue as it is not fixed.

**Comment by gfoldv** [comment]
@joesus Indeed the ticket was not meant to report a bug, but rather a feature request.
Here is my feedback if you could pass it to the involved parties:

As the official blog post states "When using the limited version of Facebook Login, the fact that a person used Facebook Login with this iOS app will not be used to personalize or measure advertising effectiveness.", I would expect that from both the user and the developer perspective the experience stays the same. This includes to get the same basic properties - e-mail, picture and separate name fields - as it was provided with the "traditional" login.

Thanks

**Comment by isimpson** [comment]
@joesus Would it be possible to reopen this issue as an `enhancement` as we still need this for implementing limited login correctly.

**Comment by YaroYaro8** [comment]
ហាយ

**Comment by BrentMifsud** [comment]
I am having this issue along with email being empty in version 9.3.0
