### ISSUE TITLE
Bitcode issue

### ISSUE THREAD

**Issue by iago849** [facebook/facebook-ios-sdk#1679]
## Checklist

- [ x] I've updated to the latest released version of the SDK
- [x ] I've searched for existing [GitHub issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [ x] I've looked for existing answers on [Stack Overflow](https://facebook.stackoverflow.com), the [Facebook Developer Community Forum](https://developers.facebook.com/community/) and the [Facebook Developers Group](https://www.facebook.com/groups/fbdevelopers)
- [ x] I've read the [Code of Conduct](https://github.com/facebook/facebook-ios-sdk/blob/master/CODE_OF_CONDUCT.md)
- [ x] This issue is not security related and can safely be disclosed publicly on GitHub

## Environment

- Xcode Version: `12.4`
- Swift Version: `4.2` (if issue is Swift related)
- Installation Platform & Verison: `[Cocoapods|Carthage|Manual]` version `1.10.1`

## Goals

When archiving the build with Facebook SDK 9.0.1, there's a bitcode-related error message saying: "ld: bitcode bundle could not be generated because '/***/Pods/FacebookSDK/FBSDKLoginKit.framework/FBSDKLoginKit(LoginManager.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build file '/***/Pods/FacebookSDK/FBSDKLoginKit.framework/FBSDKLoginKit' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)"

I cannot build without bitcode support because I need WatchOS extension which is only supported for bitcode enabled.

## Expected Results

Link project successfully

## Actual Results

"ld: bitcode bundle could not be generated because '/***/Pods/FacebookSDK/FBSDKLoginKit.framework/FBSDKLoginKit(LoginManager.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build file '/***/Pods/FacebookSDK/FBSDKLoginKit.framework/FBSDKLoginKit' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)"

linker error

**Comment by iago849** [comment]
Downgrade to Facebook SDK 7.0.1 helped - but this is NOT A FIX, it's a temporary workaround. Facebook team must build latest 9.0.1 release with full bitcode support and test before shipped, otherwise noone could use the new functionality. Half of internet asks you to do this, please do not close the ticket

**Comment by joesus** [comment]
> Tried to compile from master on git (9.1.0) - works like a charm. While I cannot downgrade to 9.0.0 - it takes FBSDKLoginKit which is obviously bitcode-broken. Please, I need your resolution. For now I'll temporary upload version with 9.1.0 from git at my own risk, but I need your advice:
> 
> 1. When 9.1.0 will officially be released?

The goal is by the end of the week. :D 

> 2. Our app uses FB login and FB ads (we pay FB for impressions and users to promote our app). Is there a chance that installing from git (pod 'FacebookSDK', :git => 'https://github.com/facebook/facebook-ios-sdk') will brake anything?

There is always a risk of using the latest 'master'. I pushed a release branch with the code we're intending to release by end of week. I would be more comfortable with a client using that as it's been more thoroughly tested. Branch name is `9.1.0-rc`

**Comment by joesus** [comment]
Closing because 9.1.0 is released. Thanks!

**Comment by iago849** [comment]
Thanks so much!

**Comment by MattSkala** [comment]
We started to experience the same error during archiving after updating to 9.1.0. Are you sure the issue is resolved?

`ld: bitcode bundle could not be generated because '[...]/Pods/FacebookSDK/FBSDKLoginKit.framework/FBSDKLoginKit(LoginManager.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build file '[...]/Pods/FacebookSDK/FBSDKLoginKit.framework/FBSDKLoginKit' for architecture arm64`

Podfile.lock:
```
 - FacebookSDK (9.1.0):
    - FacebookSDK/CoreKit (= 9.1.0)
  - FacebookSDK/CoreKit (9.1.0):
    - FBSDKCoreKit (~> 9.1.0)
  - FacebookSDK/LoginKit (9.1.0):
    - FacebookSDK/CoreKit
  - FBSDKCoreKit (9.1.0):
    - FBSDKCoreKit/Basics (= 9.1.0)
    - FBSDKCoreKit/Core (= 9.1.0)
  - FBSDKCoreKit/Basics (9.1.0)
  - FBSDKCoreKit/Core (9.1.0):
    - FBSDKCoreKit/Basics
```

The temporary workaround is to downgrade back to 9.0.0.

**Comment by tsapeta** [comment]
I'm also experiencing the same issue for release builds — @joesus do you have any official solution to this problem, other than compiling LoginKit from sources from GitHub? I can confirm that all `9.0.0`, `9.0.1`, `9.1.0` are bitcode-broken.

**Comment by joesus** [comment]
You can use the individual pods ex: "pod FBSDKCoreKit", "pod FBSDKLoginKit", "pod FBSDKShareKit" as a temporary workaround while we debug why the prebuilt static libraries used by the FacebookSDK pod are missing bitcode.

**Comment by ide** [comment]
I've found the error persists after building the libraries from source using the release scripts (`scripts/run.sh release github static`), unzipping the build artifacts, and copying the framework binaries into a project's Pods directory. Perhaps this isn't surprising, since the released binaries were built with the same script, but it indicates a problem with the build script rather than a botched release.

At the same time, running `otool -arch arm64 -l FBSDKLoginKit | grep -A1 'sectname __bitcode'` on the binary shows it should contain bitcode. The same is true for `LoginManager.o`, which shows up in the build error message. And all the Xcode project configurations have ENABLE_BITCODE and `-fembed-bitcode` set, and enabling bitcode for `BuildAllKits` doesn't appear to have an effect.

**Comment by joesus** [comment]
> a problem with the build script rather than a botched release.

I think we may be missing. 

BITCODE_GENERATION_MODE=bitcode

**Comment by ide** [comment]
I tried setting that flag in the base FBSDKLoginKit build settings and didn't have any luck. I'm currently trying a combination of adding that flag to iOS.xcconfig and also building the libraries with `xcodebuild clean archive` instead of `clean build`. Technically the `BITCODE_GENERATION_MODE` and `-fembed-bitcode` flags should add bitcode to the binaries but perhaps those settings aren't applied 100% of the time when using `build` instead of `archive`, which should honor `ENABLE_BITCODE`.

**Comment by ide** [comment]
I was looking in the wrong place and found that `BITCODE_GENERATION_MODE = bitcode` appears to get past this error. I put up a small PR to take care of this.

I could be mistaken but since the error looks related to the binary and not CocoaPods, it's probably straightforward and a matter of putting in time to add a CI step to create a tiny smoke test project that depends on the release artifacts and builds an app archive.

**Comment by iago849** [comment]
@joesus 
1) as @ide mentioned, "manual" "pod FBSDKCoreKit" etc won't even compile, I don't say archive for all architectures.
2) as a very temporary and dirty solution, the one way to compile and go to appstore with 9+ and bitcode (which we obviously need when distributing for Apple Watch target)

pod 'FacebookSDK', :git => 'https://github.com/facebook/facebook-ios-sdk', :branch => '9.1.0-rc'
pod 'FacebookSDK/LoginKit', :git => 'https://github.com/facebook/facebook-ios-sdk', :branch => '9.1.0-rc'
pod 'FacebookSDK/ShareKit', :git => 'https://github.com/facebook/facebook-ios-sdk', :branch => '9.1.0-rc'
pod 'FBSDKCoreKit', :git => 'https://github.com/facebook/facebook-ios-sdk', :branch => '9.1.0-rc'
pod 'FBSDKLoginKit', :git => 'https://github.com/facebook/facebook-ios-sdk', :branch => '9.1.0-rc'

that I guarantee - compiles, archives and accepts by Appstore
3) Besides all emotions that Facebook SDK causes in my mind and other million iOS devs - you should add a checkmark for all future releases before you ship new SDK version:
- create blank project with Apple Watch target (ensures bitcode)
- point to SDK exactly as you say on git page, run pod init/pod install
- product->archive, wait until done (ensures it's compiled for every architecture)

Guys, literally we can't live without Facebook - any marketing guy wants your ads, login via Facebook, etc. But bitcode support is broken in almost every release after 7.0.1 - latest stable one. And you force us to update to 9.x since others are deprecated. Our manager and marketing guys force us, eat our nerves every day. And army of iOS devs suffer every day. Plz, help us!

In case you don't have resources to investigate and fix it once and forever - I can recommend a person who will do it once and forever for relatively small money.

**Comment by joesus** [comment]
This should be fixed by https://github.com/facebook/facebook-ios-sdk/pull/1698.

**Comment by shamilovtim** [comment]
Any ETA on cutting a release? We had to disable bitcode due to this.

**Comment by joesus** [comment]
> Any ETA on cutting a release? We had to disable bitcode due to this.

The plan is to release a patch or minor version next week.
