### ISSUE TITLE
Unable to compile on Xcode 13

### ISSUE THREAD

**Issue by Vincent-Loi** [facebook/facebook-ios-sdk#1765]
## Checklist

- [X] I've updated to the latest released version of the SDK
- [X] I've searched for existing [GitHub issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [X] I've looked for existing answers on [Stack Overflow](https://facebook.stackoverflow.com), the [Facebook Developer Community Forum](https://developers.facebook.com/community/) and the [Facebook Developers Group](https://www.facebook.com/groups/fbdevelopers)
- [X] I've read the [Code of Conduct](https://github.com/facebook/facebook-ios-sdk/blob/master/CODE_OF_CONDUCT.md)
- [X] This issue is not security related and can safely be disclosed publicly on GitHub

## Environment

Describe your dev environment here, giving as many details as possible. If you have them, make sure to include:

- Xcode Version: `13.0`
- Swift Version: `5.5`
- Installation Platform & Verison: `Swift Package Manager`

## Goals

Compile an iOS project with Facebook SDK installed via SPM.

## Expected Results

Able to build.

## Actual Results

Produces the below errors:

`Failed to build module 'Accelerate'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.5 (swiftlang-1300.0.17.216 clang-1300.0.18.1)', while this compiler is 'Apple Swift version 5.5 (swiftlang-1300.0.19.104 clang-1300.0.18.4)'). Please select a toolchain which matches the SDK.`

`/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.0.sdk/usr/lib/swift/Accelerate.swiftmodule/armv7-apple-ios.swiftinterface:591:6: Enum cases with associated values cannot be marked potentially unavailable with '@available'`

`/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.0.sdk/usr/lib/swift/Accelerate.swiftmodule/armv7-apple-ios.swiftinterface:2092:6: Enum cases with associated values cannot be marked potentially unavailable with '@available'`

`/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.0.sdk/usr/lib/swift/Accelerate.swiftmodule/armv7-apple-ios.swiftinterface:2094:6: Enum cases with associated values cannot be marked potentially unavailable with '@available'`

(Also spoke with Apple engineers at WWDC labs today and they suggest the toolchain used in the SDK is an older version than the public version shipped with Xcode 13 🤔)

**Comment by njuxjy** [comment]
Verified the issue was resolved in Xcode 13 beta 2.

**Comment by xuzhe** [comment]
> Verified the issue was resolved in Xcode 13 beta 2.

Have you tried archive (release)?

**Comment by njuxjy** [comment]
> > Verified the issue was resolved in Xcode 13 beta 2.
> 
> Have you tried archive (release)?
yes I archived the app. Does it not work for you?

**Comment by pepejeria** [comment]
No difference with Xcode 13 beta 2, the project still fails to compile:

```
/Users/user/Library/Developer/Xcode/DerivedData/project/SourcePackages/checkouts/facebook-ios-sdk/Sources/FacebookCore/Imports.swift:19:8: Failed to build module 'Accelerate'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.5 (swiftlang-1300.0.20.4 clang-1300.0.21.1)', while this compiler is 'Apple Swift version 5.5 (swiftlang-1300.0.20.104 clang-1300.0.21.1)'). Please select a toolchain which matches the SDK.
```

**Comment by njuxjy** [comment]
> No difference with Xcode 13 beta 2, the project still fails to compile:
> 
> ```
> /Users/user/Library/Developer/Xcode/DerivedData/project/SourcePackages/checkouts/facebook-ios-sdk/Sources/FacebookCore/Imports.swift:19:8: Failed to build module 'Accelerate'; 
> this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.5 (swiftlang-1300.0.20.4 clang-1300.0.21.1)', while this compiler is 'Apple Swift version 5.5 (swiftlang-1300.0.20.104 clang-1300.0.21.1)'). 
> Please select a toolchain which matches the SDK.
> ```

did you use SPM ? it looks like for SPM it is still not working https://github.com/onevcat/Kingfisher/issues/1725

**Comment by pepejeria** [comment]
@njuxjy yes, I am using SPM. Thanks for the info.

**Comment by xuzhe** [comment]
> > > Verified the issue was resolved in Xcode 13 beta 2.
> > 
> > 
> > Have you tried archive (release)?
> 
> yes I archived the app. Does it not work for you?

I can build for debug but not for archive (release).
BTW I am using CocoaPods to import the frameworks.

**Comment by akshitzaveri** [comment]
I am also using Cocoapods and facing the same issue.

**Comment by joesus** [comment]
This appears to be an issue with the Accelerate framework in the current beta and should be fine once that is fixed in a later beta version.

**Comment by joesus** [comment]
Appears to be resolved in beta 3 and 4

**Comment by lakshminarayana254** [comment]
getting same issue in XCode 13 beta 2.xip , Any solutions please...

**Comment by AndrewKochulab** [comment]
The same issue on the officially released Xcode 13 version

**Comment by aaparth** [comment]
I am also getting the same issue on the release version of 13

**Comment by EralpBay** [comment]
same issue..

**Comment by canbalkaya** [comment]
Same issue.

**Comment by LittleTruck** [comment]
I had this problem with both 13.3 and 13.2, but 13.0 worked fine

**Comment by jfostersn** [comment]
Thanks

**Comment by maanstone** [comment]
في ثلاثاء، ٢٩ مارس، ٢٠٢٢ في ٤:٥٦ م، كتب jackie johnson <
***@***.***>:
