### ISSUE TITLE
12.2.1 Memory Leak

### ISSUE THREAD

**Issue by Sunrise17** [facebook/facebook-ios-sdk#1984]
### Checklist before submitting a bug report

- [X] I've updated to the latest released version of the SDK
- [X] I've searched for existing [GitHub issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [X] I've looked for existing answers on [Stack Overflow](https://facebook.stackoverflow.com), the [Facebook Developer Community Forum](https://developers.facebook.com/community/) and the [Facebook Developers Group](https://www.facebook.com/groups/fbdevelopers)
- [X] I've read the [Code of Conduct](https://github.com/facebook/facebook-ios-sdk/blob/main/CODE_OF_CONDUCT.md)
- [X] This issue is not security related and can safely be disclosed publicly on GitHub

### Xcode version

13.2

### Facebook iOS SDK version

12.2.1

### Dependency Manager

CocoaPods

### SDK Framework

Login

### Goals

I have updated login and share pods to 12.2.1 and memory leaked occurred when i have checked from instruments. After i have disabled code `ApplicationDelegate.shared.application(application, didFinishLaunchingWithOptions: launchOptions)` in AppDelegate, it has gone. It is caused by the FB SDK.

### Expected results

Issues happened by FB SDK, needs to be corrected asap.

### Actual results

[Instruments Leaks Result](https://ibb.co/7njK5wT)

**Comment by joesus** [comment]
Does this only happen when you open from a web browser? Also, are you able to provide a sample app to reproduce this?

**Comment by MrGobert** [comment]
I'm getting this same memory leak issue as well. Noticed when running Instruments in Xcode. 

Instruments specifically calls out these areas:
FBSDKErrorConfiguration
FBSDKErrorRecoveryConfiguration
FBSDKServerConfiguration

**Comment by jfostersn** [comment]
What is a big

**Comment by jfostersn** [comment]
What is a bug

**Comment by samodom** [comment]
@Sunrise17 We were able to reproduce a memory leak from the authentication token factory class and have created a possible fix for this issue that we expect to ship in our next release.  We will leave this issue open until that release and hope that you'll be able to confirm that it is fixed at that time.

**Comment by dxshindeo** [comment]
I would like for this to be re-opened - the issue is still here and is reproducible.
Tested on iOS 16, iPhone 14 emulator.
I have downloaded the latest (at the time of writing) swift package `facebook-ios-sdk: 15.1.0`.
The module which is imported in app is `Facebook Login`.

Run the "Instruments->Leaks" on an empty Swift project - no leaks.
But do what OP has said and we immediately get 23 memory leaks:

![Screenshot 2022-11-04 at 15 41 52](https://user-images.githubusercontent.com/18443089/199986953-f9394981-a4fc-42ae-9306-f53870bb7eb1.png)

**Comment by Anoopkmr1** [comment]
We are still facing the same issue, please let us know if there is any update regarding this.

**Comment by alpha-moisol** [comment]
Any progress here?

**Comment by efstathiosntonas** [comment]
Getting memory leaks too :/
